version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ecoshub/jin
    environment:
      TEST_RESULTS: /tmp/test-results 
    docker:
    - image: circleci/golang:1.9
    steps:
    - checkout
    - run: sudo apt-get install -y node
    - run: node --version
    - run: go get -v -t -d
    - run: go test -v