version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ecoshub/jin
    docker:
    - image: circleci/golang:1.9
    - image: circleci/node
    steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -v ./...